# Generated by Django 3.2.24 on 2024-02-11 05:30

from django.db import migrations, models
import django.db.models.deletion
import management_app.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.TextField()),
                (
                    "contact_number",
                    models.PositiveIntegerField(
                        validators=[management_app.validators.validate_phone_number]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("quantity_in_stock", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="C:\\Users\\admni\\Documents\\inventory_management_system\\files/uploaded_files/",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management_app.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventories",
            },
        ),
    ]
